### ISSUE TITLE
Generate service manifests not finding Docker credentials

### ISSUE THREAD

**Issue by MitchellCash** [hyscale/hyscale#307]
Summary : 
---
**Steps to replicate:**

1. I ran `docker login registry.hub.docker.com` successfully
2. Creds stored in `~/.docker/config/json`:

   ```json
   {
       "registry.hub.docker.com": {
           "auth": "****"
       }
       },
       "HttpHeaders": {
           "User-Agent": "Docker-Client/19.03.12 (darwin)"
       }
   }
   ```

3. `testservice.hspec` looks like:

   ```yaml
   name: testservice

   image:
       registry: registry.hub.docker.com
       name: ***/test
       tag: 1.0.0

   external: true

   ports:
       - port: 3001/tcp
   ```

4. Receive the following warning:

   `[WARN]  Missing credentials for the registry registry.hub.docker.com. Please perform 'docker login registry.hub.docker.com ' to continue with the deployment`

**Expected result:**

The command can find my docker credentials and finish running.

**Actual result:**

I get the warning `[WARN]  Missing credentials for the registry registry.hub.docker.com. Please perform 'docker login registry.hub.docker.com ' to continue with the deployment`
